spring:
  devtools:
    restart:
      enabled: true

  # mysql database
  datasource:
    username: nfx
    password: 123456
    url: jdbc:mysql://8.130.48.233:3306/second_tx?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl